# Xavier Bresson, 2023
# conda env create -f environment.yml
# conda activate gnn_course
# note: It took 10 min to install the environment

name: gnn_course


channels:
  
  - conda-forge # numpy/scipy etc
  - pytorch # DL
  - dglteam # GNN
  - pyg # GNN

dependencies:

  # basic
  - python=3.8
  - numpy=1.23
  - mkl=2023.2
  - jupyter=1.0
  - ipython=8.12
  - matplotlib=3.7
  - scipy=1.10
  - networkx=3.1
  - scikit-learn=1.3
  - pandas=2.0
  - seaborn=0.13

  # non-DL
  - pymetis=2023.1
  - python-louvain=0.16

  # DL
  - pytorch=2.1.2 # DL
  - torchvision=0.16 # CV 

  # GNN
  - dgl=2.0.0 # DGL
  - pyg=2.5.1 # PyG
